// Comprehensive 50+ Top Global & Regional Languages Metadata Dictionary for International SEO
export interface LanguageMeta {
  code: string;
  name: string;
  title: string;
  desc: string;
  promptGenerator: string;
  imagePrompt: string;
  videoPrompt: string;
}

export const TOP_LANGUAGES: LanguageMeta[] = [
  { code: "en", name: "English", title: "AI Prompt Generator Free", desc: "100% Free AI Prompt Generator for ChatGPT, Claude, Gemini, Grok, Nano Banana Pro & Veo 3", promptGenerator: "AI Prompt Generator", imagePrompt: "AI Image Prompts", videoPrompt: "AI Video Prompts" },
  { code: "hi", name: "हिन्दी (Hindi)", title: "फ्री एआई प्रॉम्प्ट जेनरेटर", desc: "ChatGPT, Claude, Gemini और Veo 3 के लिए 100% मुफ्त एआई प्रॉम्प्ट जेनरेटर। बिना लॉगिन के असीमित प्रॉम्प्ट्स।", promptGenerator: "एआई प्रॉम्प्ट जेनरेटर", imagePrompt: "एआई इमेज प्रॉम्प्ट्स", videoPrompt: "एआई वीडियो प्रॉम्प्ट्स" },
  { code: "mr", name: "मराठी (Marathi)", title: "मोफत एआय प्रॉम्प्ट जनरेटर", desc: "ChatGPT, Gemini, Nano Banana आणि Veo 3 साठी मोफत एआय प्रॉम्प्ट जनरेटर. लॉगिनची आवश्यकता नाही.", promptGenerator: "एआय प्रॉम्प्ट जनरेटर", imagePrompt: "एआय फोटो प्रॉम्प्ट्स", videoPrompt: "एआय व्हिडिओ प्रॉम्प्ट्स" },
  { code: "es", name: "Español (Spanish)", title: "Generador de Prompts AI Gratis", desc: "Generador de prompts gratuito para ChatGPT, Claude, Gemini y Veo 3. Sin registro ni límites.", promptGenerator: "Generador de Prompts AI", imagePrompt: "Prompts de Imágenes AI", videoPrompt: "Prompts de Video AI" },
  { code: "fr", name: "Français (French)", title: "Générateur de Prompts IA Gratuit", desc: "Créez des prompts IA pour ChatGPT, Claude, Gemini et Veo 3 gratuitement et sans inscription.", promptGenerator: "Générateur de Prompts IA", imagePrompt: "Prompts Images IA", videoPrompt: "Prompts Vidéo IA" },
  { code: "de", name: "Deutsch (German)", title: "Kostenloser KI Prompt Generator", desc: "Bester kostenloser KI Prompt Generator für ChatGPT, Claude, Gemini, Veo 3 und Midjourney ohne Login.", promptGenerator: "KI Prompt Generator", imagePrompt: "KI Bild Prompts", videoPrompt: "KI Video Prompts" },
  { code: "pt", name: "Português (Portuguese)", title: "Gerador de Prompts IA Grátis", desc: "Gerador de prompts de IA grátis para ChatGPT, Claude, Gemini e Veo 3. Sem login e ilimitado.", promptGenerator: "Gerador de Prompts IA", imagePrompt: "Prompts de Imagem IA", videoPrompt: "Prompts de Vídeo IA" },
  { code: "ja", name: "日本語 (Japanese)", title: "無料 AIプロンプトジェネレーター", desc: "ChatGPT、Claude、Gemini、Nano Banana、Veo 3向けの無料AIプロンプト作成ツール。ログイン不要。", promptGenerator: "AIプロンプトジェネレーター", imagePrompt: "AI画像プロンプト", videoPrompt: "AI動画プロンプト" },
  { code: "ko", name: "한국어 (Korean)", title: "무료 AI 프롬프트 생성기", desc: "ChatGPT, Claude, Gemini, Veo 3를 위한 100% 무료 AI 프롬프트 생성기. 로그인 필요 없음.", promptGenerator: "AI 프롬프트 생성기", imagePrompt: "AI 이미지 프롬프트", videoPrompt: "AI 비디오 프롬프트" },
  { code: "zh-cn", name: "简体中文 (Simplified Chinese)", title: "免费 AI 提示词生成器", desc: "适用于 ChatGPT、Claude、Gemini、Nano Banana 和 Veo 3 的 100% 免费 AI 提示词生成器，无需注册。", promptGenerator: "AI 提示词生成器", imagePrompt: "AI 图片提示词", videoPrompt: "AI 视频提示词" },
  { code: "zh-tw", name: "繁體中文 (Traditional Chinese)", title: "免費 AI 提示詞產生器", desc: "專為 ChatGPT、Claude、Gemini 與 Veo 3 設計的免費 AI 提示詞產生器，完全無須登入。", promptGenerator: "AI 提示詞產生器", imagePrompt: "AI 圖片提示詞", videoPrompt: "AI 影片提示詞" },
  { code: "ar", name: "العربية (Arabic)", title: "مولد أوامر الذكاء الاصطناعي مجاناً", desc: "أفضل مولد أوامر مجاني لـ ChatGPT و Claude و Gemini و Veo 3 بدون تسجيل أو حدود.", promptGenerator: "مولد أوامر الذكاء الاصطناعي", imagePrompt: "أوامر صور الذكاء الاصطناعي", videoPrompt: "أوامر فيديو الذكاء الاصطناعي" },
  { code: "bn", name: "বাংলা (Bengali)", title: "ফ্রি এআই প্রম্পট জেনারেটর", desc: "ChatGPT, Claude, Gemini এবং Veo 3 এর জন্য সম্পূর্ণ বিনামূল্যে আনলিমিটেড এআই প্রম্পট জেনারেটর।", promptGenerator: "এআই প্রম্পট জেনারেটর", imagePrompt: "এআই ইমেজ প্রম্পট", videoPrompt: "এআই ভিডিও প্রম্পট" },
  { code: "ru", name: "Русский (Russian)", title: "Бесплатный Генератор Промптов ИИ", desc: "100% бесплатный генератор промптов для ChatGPT, Claude, Gemini, Veo 3 без регистрации.", promptGenerator: "Генератор Промптов ИИ", imagePrompt: "Промпты для картинок ИИ", videoPrompt: "Промпты для видео ИИ" },
  { code: "it", name: "Italiano (Italian)", title: "Generatore di Prompt AI Gratis", desc: "Miglior generatore di prompt AI gratuito per ChatGPT, Claude, Gemini e Veo 3 senza registrazione.", promptGenerator: "Generatore di Prompt AI", imagePrompt: "Prompt Immagini AI", videoPrompt: "Prompt Video AI" },
  { code: "tr", name: "Türkçe (Turkish)", title: "Ücretsiz Yapay Zeka Komut Oluşturucu", desc: "ChatGPT, Claude, Gemini ve Veo 3 için %100 ücretsiz sınırsız prompt üretici. Kayıt gerektirmez.", promptGenerator: "AI Prompt Oluşturucu", imagePrompt: "AI Görsel Komutları", videoPrompt: "AI Video Komutları" },
  { code: "vi", name: "Tiếng Việt (Vietnamese)", title: "Trình Tạo Prompt AI Miễn Phí", desc: "Tạo prompt AI miễn phí cho ChatGPT, Claude, Gemini, Veo 3 không giới hạn và không cần đăng ký.", promptGenerator: "Trình Tạo Prompt AI", imagePrompt: "Prompt Tạo Ảnh AI", videoPrompt: "Prompt Tạo Video AI" },
  { code: "th", name: "ไทย (Thai)", title: "เครื่องมือสร้าง Prompt AI ฟรี", desc: "เครื่องมือสร้างคำสั่ง AI สำหรับ ChatGPT, Claude, Gemini และ Veo 3 ฟรี 100% ไม่ต้องเข้าสู่ระบบ", promptGenerator: "สร้าง Prompt AI", imagePrompt: "คำสั่งสร้างภาพ AI", videoPrompt: "คำสั่งสร้างวิดีโอ AI" },
  { code: "id", name: "Bahasa Indonesia", title: "Generator Prompt AI Gratis", desc: "Generator prompt AI 100% gratis untuk ChatGPT, Claude, Gemini, Veo 3 tanpa login dan tanpa batas.", promptGenerator: "Generator Prompt AI", imagePrompt: "Prompt Gambar AI", videoPrompt: "Prompt Video AI" },
  { code: "ms", name: "Bahasa Melayu", title: "Penjana Prompt AI Percuma", desc: "Penjana prompt AI percuma untuk ChatGPT, Gemini, Claude dan Veo 3 tanpa perlu log masuk.", promptGenerator: "Penjana Prompt AI", imagePrompt: "Prompt Imej AI", videoPrompt: "Prompt Video AI" },
  { code: "pl", name: "Polski (Polish)", title: "Darmowy Generator Promptów AI", desc: "Najlepszy darmowy generator promptów AI do ChatGPT, Claude, Gemini i Veo 3 bez logowania.", promptGenerator: "Generator Promptów AI", imagePrompt: "Prompty Graficzne AI", videoPrompt: "Prompty Wideo AI" },
  { code: "nl", name: "Nederlands (Dutch)", title: "Gratis AI Prompt Generator", desc: "100% gratis AI-promptgenerator voor ChatGPT, Claude, Gemini en Veo 3 zonder account.", promptGenerator: "AI Prompt Generator", imagePrompt: "AI Afbeelding Prompts", videoPrompt: "AI Video Prompts" },
  { code: "sv", name: "Svenska (Swedish)", title: "Gratis AI Prompt Generator", desc: "Generera AI-prompter för ChatGPT, Claude, Gemini och Veo 3 helt gratis utan inloggning.", promptGenerator: "AI Prompt Generator", imagePrompt: "AI Bild Prompter", videoPrompt: "AI Video Prompter" },
  { code: "da", name: "Dansk (Danish)", title: "Gratis AI Prompt Generator", desc: "Bedste gratis prompt-generator til ChatGPT, Claude, Gemini og Veo 3 uden registrering.", promptGenerator: "AI Prompt Generator", imagePrompt: "AI Billed Prompts", videoPrompt: "AI Video Prompts" },
  { code: "fi", name: "Suomi (Finnish)", title: "Ilmainen AI Kehote Generaattori", desc: "Luo kehotteita ChatGPT:lle, Claudelle, Geminille ja Veo 3:lle täysin ilmaiseksi ilman kirjautumista.", promptGenerator: "AI Kehote Generaattori", imagePrompt: "AI Kuva Kehotteet", videoPrompt: "AI Video Kehotteet" },
  { code: "no", name: "Norsk (Norwegian)", title: "Gratis AI Prompt Generator", desc: "Lag AI-prompter for ChatGPT, Claude, Gemini og Veo 3 gratis uten begrensninger.", promptGenerator: "AI Prompt Generator", imagePrompt: "AI Bilde Prompts", videoPrompt: "AI Video Prompts" },
  { code: "cs", name: "Čeština (Czech)", title: "Bezplatný Generátor AI Promptů", desc: "Generátor promptů pro ChatGPT, Claude, Gemini a Veo 3 zdarma bez nutnosti registrace.", promptGenerator: "Generátor AI Promptů", imagePrompt: "AI Obrázkové Prompty", videoPrompt: "AI Video Prompty" },
  { code: "el", name: "Ελληνικά (Greek)", title: "Δωρεάν AI Prompt Generator", desc: "Δημιουργήστε prompts για ChatGPT, Claude, Gemini και Veo 3 εντελώς δωρεάν χωρίς σύνδεση.", promptGenerator: "AI Prompt Generator", imagePrompt: "AI Prompts Εικόνας", videoPrompt: "AI Prompts Βίντεο" },
  { code: "he", name: "עברית (Hebrew)", title: "מחולל פרומפטים AI בחינם", desc: "מחולל פרומפטים 100% חינם עבור ChatGPT, Claude, Gemini ו-Veo 3 ללא הרשמה וללא הגבלה.", promptGenerator: "מחולל פרומפטים AI", imagePrompt: "פרומפטים לתמונות AI", videoPrompt: "פרומפטים לווידאו AI" },
  { code: "fa", name: "فارسی (Persian)", title: "تولید کننده پرامپت هوش مصنوعی رایگان", desc: "تولید رایگان پرامپت های ChatGPT، Claude، Gemini و Veo 3 بدون نیاز به ثبت نام و ورود.", promptGenerator: "تولید کننده پرامپت AI", imagePrompt: "پرامپت تصویر هوش مصنوعی", videoPrompt: "پرامپت ویدیو هوش مصنوعی" },
  { code: "ur", name: "اردو (Urdu)", title: "مفت اے آئی پرامپٹ جنریٹر", desc: "ChatGPT، Claude، Gemini اور Veo 3 کے لیے لامحدود مفت اے آئی پرامپٹس بغیر لاگ ان۔", promptGenerator: "اے آئی پرامپٹ جنریٹر", imagePrompt: "اے آئی تصویر پرامپٹ", videoPrompt: "اے آئی ویڈیو پرامپٹ" },
  { code: "ta", name: "தமிழ் (Tamil)", title: "இலவச AI ப்ராம்ப்ட் ஜெனரேட்டர்", desc: "ChatGPT, Claude, Gemini மற்றும் Veo 3 க்கான 100% இலவச AI ப்ராம்ப்ட் ஜெனரேட்டர்.", promptGenerator: "AI ப்ராம்ப்ட் ஜெனரேட்டர்", imagePrompt: "AI பட ப்ராம்ப்ட்", videoPrompt: "AI வீடியோ ப்ராம்ப்ட்" },
  { code: "te", name: "తెలుగు (Telugu)", title: "ఉచిత AI ప్రాంప్ట్ జెనరేటర్", desc: "ChatGPT, Claude, Gemini మరియు Veo 3 కొరకు ఉచిత AI ప్రాంప్ట్ జెనరేటర్. లాగిన్ అవసరం లేదు.", promptGenerator: "AI ప్రాంప్ట్ జెనరేటర్", imagePrompt: "AI ఇమేజ్ ప్రాంప్ట్స్", videoPrompt: "AI వీడియో ప్రాంప్ట్స్" },
  { code: "kn", name: "ಕನ್ನಡ (Kannada)", title: "ಉಚಿತ AI ಪ್ರಾಂಪ್ಟ್ ಜನರೇಟರ್", desc: "ChatGPT, Claude, Gemini ಮತ್ತು Veo 3 ಗಾಗಿ ಉಚಿತ AI ಪ್ರಾಂಪ್ಟ್ ಜನರೇಟರ್. ಯಾವುದೇ ಲಾಗಿನ್ ಅಗತ್ಯವಿಲ್ಲ.", promptGenerator: "AI ಪ್ರಾಂಪ್ಟ್ ಜನರೇಟರ್", imagePrompt: "AI ಚಿತ್ರ ಪ್ರಾಂಪ್ಟ್‌ಗಳು", videoPrompt: "AI ವೀಡಿಯೊ ಪ್ರಾಂಪ್ಟ್‌ಗಳು" },
  { code: "ml", name: "മലയാളം (Malayalam)", title: "സൗജന്യ AI പ്രോംപ്റ്റ് ജനറേറ്റർ", desc: "ChatGPT, Claude, Gemini, Veo 3 എന്നിവയ്ക്കുള്ള സൗജന്യ AI പ്രോംപ്റ്റ് ജനറേറ്റർ.", promptGenerator: "AI പ്രോംപ്റ്റ് ജനറേറ്റർ", imagePrompt: "AI ഇമേജ് പ്രോംപ്റ്റുകൾ", videoPrompt: "AI വീഡിയോ പ്രോംപ്റ്റുകൾ" },
  { code: "gu", name: "ગુજરાતી (Gujarati)", title: "મફત AI પ્રોમ્પ્ટ જનરેટર", desc: "ChatGPT, Claude, Gemini અને Veo 3 માટે મફત AI પ્રોમ્પ્ટ જનરેટર. કોઈ સાઇન-અપ જરૂરી નથી.", promptGenerator: "AI પ્રોમ્પ્ટ જનરેટર", imagePrompt: "AI ઇમેજ પ્રોમ્પ્ટ્સ", videoPrompt: "AI વિડિઓ પ્રોમ્પ્ટ્સ" },
  { code: "pa", name: "ਪੰਜਾਬੀ (Punjabi)", title: "ਮੁਫਤ AI ਪ੍ਰੋਂਪਟ ਜਨਰੇਟਰ", desc: "ChatGPT, Claude, Gemini ਅਤੇ Veo 3 ਲਈ ਮੁਫਤ AI ਪ੍ਰੋਂਪਟ ਜਨਰੇਟਰ ਬਿਨਾਂ ਕਿਸੇ ਲੌਗਇਨ ਦੇ।", promptGenerator: "AI ਪ੍ਰੋਂਪਟ ਜਨਰੇਟਰ", imagePrompt: "AI ਚਿੱਤਰ ਪ੍ਰੋਂਪਟ", videoPrompt: "AI ਵੀਡੀਓ ਪ੍ਰੋਂਪਟ" },
  { code: "uk", name: "Українська (Ukrainian)", title: "Безкоштовний Генератор Промптів AI", desc: "100% безкоштовний генератор промптів для ChatGPT, Claude, Gemini та Veo 3 без реєстрації.", promptGenerator: "Генератор Промптів AI", imagePrompt: "Промпти для зображень AI", videoPrompt: "Промпти для відео AI" },
  { code: "ro", name: "Română (Romanian)", title: "Generator Prompturi AI Gratuit", desc: "Generator gratuit de prompturi pentru ChatGPT, Claude, Gemini și Veo 3 fără cont.", promptGenerator: "Generator Prompturi AI", imagePrompt: "Prompturi Imagini AI", videoPrompt: "Prompturi Video AI" },
  { code: "hu", name: "Magyar (Hungarian)", title: "Ingyenes AI Prompt Generátor", desc: "Ingyenes AI prompt generátor ChatGPT, Claude, Gemini és Veo 3 modellekhez bejelentkezés nélkül.", promptGenerator: "AI Prompt Generátor", imagePrompt: "AI Kép Promptek", videoPrompt: "AI Videó Promptek" },
  { code: "sk", name: "Slovenčina (Slovak)", title: "Bezplatný Generátor AI Promptov", desc: "Generujte promptovacie príkazy pre ChatGPT, Claude, Gemini a Veo 3 zadarmo a bez prihlásenia.", promptGenerator: "Generátor AI Promptov", imagePrompt: "AI Obrázkové Prompty", videoPrompt: "AI Video Prompty" },
  { code: "bg", name: "Български (Bulgarian)", title: "Безплатен Генератор на AI Промптове", desc: "100% безплатен генератор на промптове за ChatGPT, Claude, Gemini и Veo 3 без регистрация.", promptGenerator: "Генератор на AI Промптове", imagePrompt: "AI Изображения Промптове", videoPrompt: "AI Видео Промптове" },
  { code: "sr", name: "Srpski (Serbian)", title: "Besplatan AI Prompt Generator", desc: "Besplatan generator promptova za ChatGPT, Claude, Gemini i Veo 3 bez prijave i bez limita.", promptGenerator: "AI Prompt Generator", imagePrompt: "AI Slike Promptovi", videoPrompt: "AI Video Promptovi" },
  { code: "hr", name: "Hrvatski (Croatian)", title: "Besplatni AI Generator Promptova", desc: "Izradite prompte za ChatGPT, Claude, Gemini i Veo 3 potpuno besplatno bez registracije.", promptGenerator: "AI Generator Promptova", imagePrompt: "AI Slikovni Prompti", videoPrompt: "AI Video Prompti" },
  { code: "lt", name: "Lietuvių (Lithuanian)", title: "Nemokamas AI Užuominų Generatorius", desc: "Nemokamas AI promptų generatorius ChatGPT, Claude, Gemini ir Veo 3 be prisijungimo.", promptGenerator: "AI Promptų Generatorius", imagePrompt: "AI Vaizdų Promptai", videoPrompt: "AI Video Promptai" },
  { code: "lv", name: "Latviešu (Latvian)", title: "Bezmaksas AI Uzvedņu Ģenerators", desc: "100% bezmaksas AI promptu ģenerators ChatGPT, Claude, Gemini un Veo 3 bez reģistrācijas.", promptGenerator: "AI Promptu Ģenerators", imagePrompt: "AI Attēlu Prompti", videoPrompt: "AI Video Prompti" },
  { code: "et", name: "Eesti (Estonian)", title: "Tasuta AI Viipade Generaator", desc: "Genereeri viipasid ChatGPT, Claude, Gemini ja Veo 3 jaoks tasuta ja ilma sisselogimiseta.", promptGenerator: "AI Viipade Generaator", imagePrompt: "AI Pildi Viibad", videoPrompt: "AI Video Viibad" },
  { code: "sl", name: "Slovenščina (Slovenian)", title: "Brezplačni AI Generator Pozivov", desc: "Ustvarite pozive za ChatGPT, Claude, Gemini in Veo 3 popolnoma brezplačno brez prijave.", promptGenerator: "AI Generator Pozivov", imagePrompt: "AI Pozivi za Slike", videoPrompt: "AI Pozivi za Video" },
  { code: "sw", name: "Kiswahili (Swahili)", title: "Jenereta ya Bure ya AI Prompt", desc: "Jenereta ya bure ya maagizo ya AI kwa ChatGPT, Claude, Gemini na Veo 3 bila kuingia.", promptGenerator: "Jenereta ya AI Prompt", imagePrompt: "AI Maagizo ya Picha", videoPrompt: "AI Maagizo ya Video" },
  { code: "fil", name: "Filipino (Tagalog)", title: "Libreng AI Prompt Generator", desc: "100% libreng AI prompt generator para sa ChatGPT, Claude, Gemini at Veo 3 nang walang login.", promptGenerator: "AI Prompt Generator", imagePrompt: "AI Larawan Prompts", videoPrompt: "AI Video Prompts" }
];
