import { NextRequest, NextResponse } from "next/server";

export const maxDuration = 60;

export async function POST(req: NextRequest) {
  try {
    const { text } = await req.json();

    if (!text || typeof text !== "string" || !text.trim()) {
      return NextResponse.json({ error: "Text is required for AI detection" }, { status: 400 });
    }

    const apiKey = process.env.GEMINI_API_KEY;
    if (!apiKey) {
      return NextResponse.json({ error: "API key is not configured" }, { status: 500 });
    }

    const systemPrompt = `You are a world-class AI Content Forensic Detector & Linguistic Auditor (similar to Turnitin / GPTZero / Originality.ai).
The user provides a piece of text (or prompt).

CRITICAL REQUIREMENT:
1. Detect which language the user submitted.
2. If the user submitted English or general text, write your entire analysis and report in professional English. If the user explicitly typed in a non-English language (e.g. Spanish, French, German), you may respond in that language or English, but keep all verdicts, explanations, and structure clear and professional. Never inject unprompted translations.
3. Analyze the text deeply:
   - Identify which exact sentences or phrases were generated by AI (detect repetitive syntax, sterile corporate phrasing, robotic patterns, lack of personal voice).
   - Estimate an accurate AI Probability Score (0% to 100%).
   - Highlight the exact words or phrases that sound like AI.
   - Explain how to make it sound authentically human.

Respond strictly in valid JSON matching this schema (no markdown formatting, no code block backticks):
{
  "detectedLanguage": "Name of language detected (e.g. English, Spanish, etc.)",
  "aiScore": 85,
  "verdict": "Short verdict in clear English (e.g. Highly Likely AI-Generated / Mostly Human-Written / Mixed)",
  "flaggedPhrases": ["Exact phrase 1 that sounds like AI", "Exact phrase 2"],
  "analysis": "Detailed 2-3 paragraph breakdown explaining WHY these parts are AI-written with linguistic evidence.",
  "humanizedSuggestion": "Rewritten version of the user text that sounds 100% human and natural."
}`;

    const payload = {
      contents: [
        {
          parts: [
            { text: systemPrompt },
            { text: `User Text to analyze:\n"""\n${text.trim()}\n"""` },
          ],
        },
      ],
      generationConfig: {
        responseMimeType: "application/json",
        temperature: 0.1,
      },
    };

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      }
    );

    if (!response.ok) {
      const err = await response.text();
      console.error("Gemini AI detector error:", err);
      return NextResponse.json({ error: "Failed to audit text with AI" }, { status: 500 });
    }

    const data = await response.json();
    const rawText = data?.candidates?.[0]?.content?.parts?.[0]?.text;
    if (!rawText) return NextResponse.json({ error: "No response from AI" }, { status: 500 });

    let parsed;
    try {
      parsed = JSON.parse(rawText);
    } catch {
      const cleaned = rawText.replace(/```json/g, "").replace(/```/g, "").trim();
      parsed = JSON.parse(cleaned);
    }

    return NextResponse.json({ success: true, data: parsed });
  } catch (err: any) {
    console.error("AI detector route error:", err);
    return NextResponse.json({ error: err.message || "Internal server error" }, { status: 500 });
  }
}
